htaic/helm-charts

.github/workflows/HelmReleaseTest.yml

fix: revert auto version

---

.github/workflows/HelmReleaseTest.yml

fix: already exists

---

charts/microauthservice/dependency_chart/hasura/templates/ingressroute.yaml
charts/microauthservice/dependency_chart/hasura/templates/middleware.yaml

fix: helm auth service middleware

---

charts/microauthservice/Chart.yaml

fix: bump version

---

charts/baseline/Chart.yaml
charts/baseline/values.yaml.Example
charts/microauthservice/Chart.yaml

fix: update versions and postgres name

---

charts/auth-service/Chart.yaml
charts/auth-service/dependency_chart/postgresql/Chart.yaml
charts/auth-service/dependency_chart/postgresql/values.yaml

fix: a small bug with postgres auto-scaling

---

charts/baseline-ory/Chart.yaml

IA-16 bumping the chart version now that it's built

---

charts/faux-auth-service/Chart.yaml
charts/faux-auth-service/templates/deployment.yaml
charts/microfrontend/Chart.yaml
charts/microfrontend/templates/deployment.yaml

fix: apply now label to force rerun for latest

---

charts/postgresql/Chart.yaml
charts/postgresql/dumpdb.sh

adding a dump script for the postgres chart

fix: update dump script

---

charts/postgresql/templates/backupcron.yaml
charts/postgresql/templates/deployment.yaml
storageclass.yml

fix: fix issues with efs and data backup

---

charts/organization-frontend/.helmignore
charts/organization-frontend/Chart.yaml
charts/organization-frontend/NOTES.txt
charts/organization-frontend/charts/organization-backend/.helmignore
charts/organization-frontend/charts/organization-backend/Chart.yaml
charts/organization-frontend/charts/organization-backend/templates/_helpers.tpl
charts/organization-frontend/charts/organization-backend/templates/deployment.yaml
charts/organization-frontend/charts/organization-backend/templates/hpa.yaml
charts/organization-frontend/charts/organization-backend/templates/service.yaml
charts/organization-frontend/charts/organization-backend/templates/serviceaccount.yaml
charts/organization-frontend/charts/organization-backend/values.yaml
charts/organization-frontend/charts/organization-creation/.helmignore
charts/organization-frontend/charts/organization-creation/Chart.yaml
charts/organization-frontend/charts/organization-creation/templates/_helpers.tpl
charts/organization-frontend/charts/organization-creation/templates/deployment.yaml
charts/organization-frontend/charts/organization-creation/templates/hpa.yaml
charts/organization-frontend/charts/organization-creation/templates/service.yaml
charts/organization-frontend/charts/organization-creation/templates/serviceaccount.yaml
charts/organization-frontend/charts/organization-creation/values.yaml
charts/organization-frontend/templates/_helpers.tpl
charts/organization-frontend/templates/deployment.yaml
charts/organization-frontend/templates/hpa.yaml
charts/organization-frontend/templates/ingressroute.yaml
charts/organization-frontend/templates/middleware.yaml
charts/organization-frontend/templates/service.yaml
charts/organization-frontend/templates/serviceaccount.yaml
charts/organization-frontend/values.yaml.Example

feat: new helm chart

---

charts/redis/Chart.yaml
charts/redis/templates/_helpers.tpl
charts/redis/templates/deployment.yaml
charts/redis/templates/secret.yaml
charts/redis/templates/service.yaml
charts/redis/templates/serviceaccount.yaml
charts/redis/values.yaml.Example

feat: redis helm chart with builtin password

---

charts/edge-background-service/Chart.yaml
charts/edge-background-service/charts/dcs/Chart.yaml
charts/edge-background-service/charts/dcs/templates/_helpers.tpl
charts/edge-background-service/charts/dcs/templates/deployment.yaml
charts/edge-background-service/charts/dcs/templates/service.yaml
charts/edge-background-service/charts/dcs/templates/serviceaccount.yaml
charts/edge-background-service/charts/dcs/values.yaml
charts/edge-background-service/charts/edgeccs/Chart.yaml
charts/edge-background-service/charts/edgeccs/templates/_helpers.tpl
charts/edge-background-service/charts/edgeccs/templates/deployment.yaml
charts/edge-background-service/charts/edgeccs/templates/service.yaml
charts/edge-background-service/charts/edgeccs/templates/serviceaccount.yaml
charts/edge-background-service/charts/edgeccs/values.yaml
charts/edge-background-service/charts/keymanager/Chart.yaml
charts/edge-background-service/charts/keymanager/templates/_helpers.tpl
charts/edge-background-service/charts/keymanager/templates/deployment.yaml
charts/edge-background-service/charts/keymanager/templates/service.yaml
charts/edge-background-service/charts/keymanager/templates/serviceaccount.yaml
charts/edge-background-service/charts/keymanager/values.yaml
charts/edge-background-service/values.yaml

test: first pass at helm chart

---

charts/edge-services/Chart.yaml
charts/edge-services/charts/scs/templates/service.yaml

Updated the selector to match the label from the scs deployment
- [ X ] 버그 수정 / Bugfix / Corrección de Error
* [DEVO-231](https://htw-cloud.atlassian.net/browse/DEVO-231)

updating the selector to match scs deployment

---

charts/edge-services/Chart.yaml
charts/edge-services/values.yaml

chore: add sql

---

charts/edge-services-cloud/Chart.yaml
charts/edge-services-cloud/charts/device-installer/Chart.yaml
charts/edge-services-cloud/charts/device-installer/templates/_helpers.tpl
charts/edge-services-cloud/charts/device-installer/templates/deployment.yaml
charts/edge-services-cloud/charts/device-installer/templates/ingressroute.yaml
charts/edge-services-cloud/charts/device-installer/templates/middleware.yaml
charts/edge-services-cloud/charts/device-installer/templates/service.yaml
charts/edge-services-cloud/charts/device-installer/templates/serviceaccount.yaml
charts/edge-services-cloud/charts/device-installer/values.yaml
charts/edge-services-cloud/charts/edgeauth/Chart.yaml
charts/edge-services-cloud/charts/edgeauth/templates/_helpers.tpl
charts/edge-services-cloud/charts/edgeauth/templates/deployment.yaml
charts/edge-services-cloud/charts/edgeauth/templates/ingressroute.yaml
charts/edge-services-cloud/charts/edgeauth/templates/middleware.yaml
charts/edge-services-cloud/charts/edgeauth/templates/service.yaml
charts/edge-services-cloud/charts/edgeauth/templates/serviceaccount.yaml
charts/edge-services-cloud/charts/edgeauth/values.yaml
charts/edge-services-cloud/charts/graphql/Chart.yaml
charts/edge-services-cloud/charts/graphql/templates/_helpers.tpl
charts/edge-services-cloud/charts/graphql/templates/deployment.yaml
charts/edge-services-cloud/charts/graphql/templates/ingressroute.yaml
charts/edge-services-cloud/charts/graphql/templates/middleware.yaml
charts/edge-services-cloud/charts/graphql/templates/service.yaml
charts/edge-services-cloud/charts/graphql/templates/serviceaccount.yaml
charts/edge-services-cloud/charts/graphql/values.yaml
charts/edge-services-cloud/values.yaml

* [DEVO-372](https://htw-cloud.atlassian.net/browse/DEVO-372)

feat: edge-services-cloud

---

.gitignore
charts/edge-services/Chart.yaml
charts/edge-services/templates/certs-configmap.yaml

test: try printf on files to do localized pathing

---

.gitignore
charts/auth-service/Chart.yaml
charts/auth-service/templates/ory-keto-ingressroute.yaml
charts/auth-service/templates/ory-keto-strip-middleware.yaml

Temporarily expose Ory Keto's Read Service to unblock frontend team. This change must be reverted soon (once Auth Service has the equivalent API).
* [IA-230](https://htw-cloud.atlassian.net/browse/IA-230)

IA-230: Temporarily expose Ory Keto's Read Service

---

charts/baseline-ory/Chart.yaml

IA-230 updating chart versions

---

charts/reporting/.helmignore
charts/reporting/Chart.yaml
charts/reporting/templates/NOTES.txt
charts/reporting/templates/_helpers.tpl
charts/reporting/templates/_required.tpl
charts/reporting/templates/deployment.yaml
charts/reporting/templates/hpa.yaml
charts/reporting/templates/ingress.yaml
charts/reporting/templates/ingressroute.yaml
charts/reporting/templates/middleware.yaml
charts/reporting/templates/secret-configmap.yaml
charts/reporting/templates/service.yaml
charts/reporting/templates/serviceaccount.yaml
charts/reporting/values.yaml.Example

Adding reporting chart for deployment to clusters. 
* [DEVO-517](https://htw-cloud.atlassian.net/browse/DEVO-517)
[DEVO-517]: https://htw-cloud.atlassian.net/browse/DEVO-517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add reporting chart

---

charts/kafka-rest/cp-kafka-rest/.helmignore
charts/kafka-rest/cp-kafka-rest/Chart.yaml
charts/kafka-rest/cp-kafka-rest/README.md
charts/kafka-rest/cp-kafka-rest/templates/Ingressroute.yaml
charts/kafka-rest/cp-kafka-rest/templates/NOTES.txt
charts/kafka-rest/cp-kafka-rest/templates/_helpers.tpl
charts/kafka-rest/cp-kafka-rest/templates/deployment.yaml
charts/kafka-rest/cp-kafka-rest/templates/external-service.yaml
charts/kafka-rest/cp-kafka-rest/templates/jmx-configmap.yaml
charts/kafka-rest/cp-kafka-rest/templates/middleware.yaml
charts/kafka-rest/cp-kafka-rest/templates/service.yaml
charts/kafka-rest/cp-kafka-rest/values-dev.yaml
charts/kafka-rest/cp-kafka-rest/values-template.yaml
charts/kafka-rest/cp-kafka-rest/values.yaml

Helm Charts to reflect manual deployment in the DEV cluster:
* [IA-286](https://htw-cloud.atlassian.net/browse/IA-286)
[IA-286]: https://htw-cloud.atlassian.net/browse/IA-286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Kafka Rest Helm Charts

---

charts/cloud-baseline/.helmignore
charts/cloud-baseline/Chart.yaml
charts/cloud-baseline/templates/_helpers.tpl
charts/cloud-baseline/templates/dashboard-middleware.yaml
charts/cloud-baseline/templates/dashboard-secret.yaml
charts/cloud-baseline/templates/dashboard-traefik.yaml
charts/cloud-baseline/values.yaml
charts/complete-auth-service/Chart.yaml
charts/complete-org-service/Chart.yaml
charts/complete-org-service/templates/deployment.yaml

add new chart for efs-csi and one without (which should have a different CSI added; bump versions to address naming issue with secrets

Edge vs cloud baselines

---

charts/kafka-rest/templates/Ingressroute.yaml
charts/kafka-rest/templates/deployment.yaml
charts/kafka-rest/templates/service.yaml

Pod Name: `kafka-rest-cp-kafka-rest-xxxxx-xxxxx -> kafka-rest-xxxxx-xxxx`
Service Name: `kafka-rest-cp-kafka-rest -> cp-kafka-rest`

Fixing Kafka Service name to be more readable

---

charts/redis/Chart.yaml
charts/redis/templates/secret.yaml
charts/redis/values.yaml

feat: add secrets values

---

charts/group-stack/charts/groups-backend/values.yaml
charts/group-stack/charts/groups-frontend/values.yaml

Groups stack chart updates

---

charts/site-stack/charts/sites-backend/values.yaml
charts/site-stack/charts/sites-frontend/values.yaml

Sites stack chart updates

---

charts/gql-devicemanager/values.yaml.Example
charts/rest-devicemanager/values.yaml.Example

- update values.yaml.Example file as latest
* [DEVO-581](https://htw-cloud.atlassian.net/browse/DEVO-581)
[DEVO-581]: https://htw-cloud.atlassian.net/browse/DEVO-581?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: update values.yaml.Example file as latest

---

charts/rest-devicemanager/Chart.yaml
charts/rest-devicemanager/templates/ingressroute.yaml

- change exception rule to only bypass POST request
* [DEVO-655](https://htw-cloud.atlassian.net/browse/DEVO-655)
[DEVO-655]: https://htw-cloud.atlassian.net/browse/DEVO-655?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVO-655 change exception rule to only bypass POST request

---

charts/cloud-baseline/templates/aws-configmap.yaml
charts/cloud-baseline/values.yaml

chore: add aws configmap to cloud

---

charts/cloud-baseline/Chart.yaml
charts/cloud-baseline/templates/aws-configmap.yaml
charts/cloud-baseline/values.yaml
charts/kafka-rest/templates/_helpers.tpl
charts/kafka-rest/templates/deployment.yaml
charts/kafka-rest/values-template.yaml
charts/kafka-rest/values.yaml

Fixing kafka host name

---

charts/video-connection-manager/.helmignore
charts/video-connection-manager/Chart.yaml
charts/video-connection-manager/templates/_helpers.tpl
charts/video-connection-manager/templates/deployment.yaml
charts/video-connection-manager/templates/service.yaml
charts/video-connection-manager/values.yaml

chore: add video connection manager DEVO-659

---

charts/kafka-rest-consumer-service/.helmignore
charts/kafka-rest-consumer-service/Chart.yaml
charts/kafka-rest-consumer-service/readme.md
charts/kafka-rest-consumer-service/templates/_helpers.tpl
charts/kafka-rest-consumer-service/templates/deployment.yaml
charts/kafka-rest-consumer-service/values.yaml
charts/kafka-rest-producer-service/.helmignore
charts/kafka-rest-producer-service/Chart.yaml
charts/kafka-rest-producer-service/readme.md
charts/kafka-rest-producer-service/templates/_helpers.tpl
charts/kafka-rest-producer-service/templates/deployment.yaml
charts/kafka-rest-producer-service/values.yaml

Bringing Helm charts for deployment for kafka-rest-node-services

---

charts/video-connection-manager/templates/_helpers.tpl
charts/video-connection-manager/templates/deployment.yaml
charts/video-connection-manager/values.yaml

Video connection manager fix

---

charts/postgresql/Chart.yaml
charts/postgresql/templates/secret-configmap.yaml

chore: add port to configmap

---

charts/core-baseline/templates/aws-configmap.yaml
charts/core-baseline/values.yaml
charts/kafka-rest-consumer-service/templates/deployment.yaml
charts/kafka-rest-producer-service/templates/deployment.yaml

chore: remove autoscale dependency

---

charts/signaling-service/.helmignore
charts/signaling-service/Chart.yaml
charts/signaling-service/templates/_helpers.tpl
charts/signaling-service/templates/_required.tpl
charts/signaling-service/templates/deployment.yaml
charts/signaling-service/templates/hpa.yaml
charts/signaling-service/templates/ingressroute.yaml
charts/signaling-service/templates/service.yaml
charts/signaling-service/templates/serviceaccount.yaml
charts/signaling-service/values.yaml

Added helm chart for signaling service
Added WebSocket IngressRoute
- [ X ] 핵심 / Core / Centro
* [VID-243](https://htw-cloud.atlassian.net/browse/VID-243)
[VID-243]: https://htw-cloud.atlassian.net/browse/VID-243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

added helm chart for signaling services

---

charts/rtsp-service/.helmignore
charts/rtsp-service/Chart.yaml
charts/rtsp-service/templates/_helpers.tpl
charts/rtsp-service/templates/_required.tpl
charts/rtsp-service/templates/deployment.yaml
charts/rtsp-service/templates/hpa.yaml
charts/rtsp-service/templates/ingressroute.yaml
charts/rtsp-service/templates/service.yaml
charts/rtsp-service/templates/serviceaccount.yaml
charts/rtsp-service/values.yaml

added helm chart for rtsp service
- [ X ] 핵심 / Core / Centro
* [DEVO-716](https://htw-cloud.atlassian.net/browse/DEVO-716)
[DEVO-716]: https://htw-cloud.atlassian.net/browse/DEVO-716?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

added helm chart for rtsp service

---

charts/rtsp-service/templates/redis-service.yaml

chore: add service alias for redis

---

charts/rtsp-service/templates/redis-service.yaml

Fixing redis-service selector value
- [ X ] 버그 수정 / Bugfix / Corrección de Error
* [VID-243](https://htw-cloud.atlassian.net/browse/VID-243)
[VID-243]: https://htw-cloud.atlassian.net/browse/VID-243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

updating baseline-redis selector

---

charts/core-edge/templates/edgeccs-deployment.yaml

chore: fix resource mapping

---

charts/edge-webrtc-service/values.yaml

chore: allow substitution

---

charts/complete-auth-service/Chart.yaml
charts/complete-auth-service/templates/deployment.yaml
charts/complete-org-service/Chart.yaml
charts/complete-org-service/templates/deployment.yaml
charts/core-baseline/values.yaml
charts/kafka-rest-consumer-service/templates/deployment.yaml
charts/kafka-rest-consumer-service/values.yaml
charts/kafka-rest-producer-service/templates/deployment.yaml
charts/kafka-rest-producer-service/values.yaml

Devo 726 fix secret

---

charts/complete-graphql-postgres-provisioner/Chart.yaml
charts/complete-graphql-postgres-provisioner/templates/_helpers.tpl
charts/complete-graphql-postgres-provisioner/templates/deployment.yaml
charts/complete-graphql-postgres-provisioner/templates/hasura-secret.yaml
charts/complete-graphql-postgres-provisioner/templates/ingressroute.yaml
charts/complete-graphql-postgres-provisioner/templates/middleware.yaml
charts/complete-graphql-postgres-provisioner/templates/service.yaml
charts/complete-graphql-postgres-provisioner/templates/serviceaccount.yaml
charts/complete-graphql-postgres-provisioner/values.yaml

Add hasura postgres

---

charts/signaling-service/values.yaml

updating signaling path to /signaling from /mqtt
- [ X ] 핵심 / Core / Centro

updating signaling path to /signaling from /mqtt

---

charts/portletmedia/.helmignore
charts/portletmedia/Chart.yaml
charts/portletmedia/templates/_helpers.tpl
charts/portletmedia/templates/deployment.yaml
charts/portletmedia/templates/hpa.yaml
charts/portletmedia/templates/ingress.yaml
charts/portletmedia/templates/ingressroute.yaml
charts/portletmedia/templates/middleware.yaml
charts/portletmedia/templates/service.yaml
charts/portletmedia/templates/serviceaccount.yaml
charts/portletmedia/values.yaml

chore: add portletmedia helm chart

---

charts/kafka-rest-consumer-service/Chart.yaml
charts/kafka-rest-consumer-service/templates/deployment.yaml
charts/kafka-rest-consumer-service/values.yaml
charts/kafka-rest-producer-service/Chart.yaml
charts/kafka-rest-producer-service/templates/deployment.yaml
charts/kafka-rest-producer-service/values.yaml

Keeping default values file in sync

---

charts/complete-graphql-postgres-provisioner/Chart.yaml
charts/complete-graphql-postgres-provisioner/templates/deployment.yaml
charts/complete-graphql-postgres-provisioner/templates/hasura-token.yaml
charts/complete-graphql-postgres-provisioner/values.yaml
charts/video-connection-manager/Chart.yaml
charts/video-connection-manager/templates/deployment.yaml
charts/video-connection-manager/values.yaml

update hasura + video-connection-manager

---

charts/cloud-baseline/Chart.yaml
charts/cloud-baseline/templates/iss-secret.yaml
charts/cloud-baseline/values.yaml
charts/core-baseline/Chart.yaml
charts/core-baseline/templates/iss-secret.yaml
charts/core-baseline/values.yaml
charts/rest-devicemanager/templates/deployment.yaml
charts/rest-devicemanager/values.yaml

Idm 1369 add initpod

---

charts/distributor-devicemanager/values.yaml
charts/gql-devicemanager/values.yaml
charts/postgresql/dumpdb.sh
charts/rest-devicemanager/values.yaml

remove -local from KR team images

---

charts/distributor-devicemanager/templates/deployment.yaml
charts/distributor-devicemanager/values.yaml
charts/gql-devicemanager/templates/deployment.yaml
charts/gql-devicemanager/values.yaml
charts/rest-devicemanager/templates/deployment.yaml
charts/rest-devicemanager/values.yaml

- You can enter multiple secretRefs and configMapRefs in the values.yaml file.
- I have modified the values file to the values required for localDM.
* [DEVO-748](https://htw-cloud.atlassian.net/browse/DEVO-748)
[DEVO-748]: https://htw-cloud.atlassian.net/browse/DEVO-748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVO-748 change local-dm image name, values file, envFrom

---

charts/rest-devicemanager/Chart.yaml

Rest Device manager should have been bumped in [153](https://github.com/htaic/helm-charts/pull/153/files)

Bumping rest device version 

---

charts/portletmedia/values.yaml

fixed portlet media domain path

---

charts/site-stack/Chart.yaml
charts/site-stack/charts/sites-backend/templates/deployment.yaml

feat: add secret hashura to sites

---

charts/kafka-rest-consumer-service/Chart.yaml
charts/kafka-rest-consumer-service/values.yaml
charts/kafka-rest-producer-service/Chart.yaml
charts/kafka-rest-producer-service/values.yaml

Updating Helm charts for kafka consumer + producer with the lastest sha tag

Updating kafka services sha

---

charts/core-baseline/Chart.yaml
charts/core-baseline/values.yaml

- [DEVO-818](https://htw-cloud.atlassian.net/browse/DEVO-818)
Kafka services does not need a config map which would require AWS information. Removing to de-clutter code. 
[DEVO-818]: https://htw-cloud.atlassian.net/browse/DEVO-818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Removing AWS reqs for edge

---

charts/complete-auth-service/Chart.yaml
charts/complete-auth-service/values.yaml

Updating auth-services

---

charts/core-baseline/Chart.yaml
charts/core-baseline/templates/aws-configmap.yaml

**Update**
- remove aws-configmap on core-baseline chart
* [DEVO-833](https://htw-cloud.atlassian.net/browse/DEVO-833)
[DEVO-833]: https://htw-cloud.atlassian.net/browse/DEVO-833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVO-833 fix: remove aws-configmap on core-baseline chart

---

charts/complete-auth-service/Chart.yaml
charts/complete-auth-service/templates/test-stack-deployment.yaml
charts/complete-auth-service/templates/test-stack-ingressroute.yaml

Left-over annotation broke the template

---

charts/complete-auth-service/Chart.yaml
charts/complete-auth-service/templates/test-stack-deployment.yaml
charts/complete-auth-service/values.yaml

Ability to override some or all env variables in the test stack

---

charts/gql-devicemanager/values.yaml
charts/rest-devicemanager/values.yaml

- Update rest-dm, gql-dm values file
* [DEVO-825](https://htw-cloud.atlassian.net/browse/DEVO-825)
[DEVO-825]: https://htw-cloud.atlassian.net/browse/DEVO-825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVO-825 update dm values

---

charts/kafka-rest-consumer-service/Chart.yaml
charts/kafka-rest-consumer-service/values.yaml

Bump kafka rest consumer

---

charts/kafka-rest-consumer-service/Chart.yaml
charts/kafka-rest-consumer-service/values.yaml

Bumped the chart version and docker tag for the kafka rest consumer service.
* [IA-552](https://htw-cloud.atlassian.net/browse/IA-552)
[IA-552]: https://htw-cloud.atlassian.net/browse/IA-552?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(IA-552): version bump for kafka consumer service

---

charts/poc-frontend/.helmignore
charts/poc-frontend/Chart.yaml
charts/poc-frontend/templates/NOTES.txt
charts/poc-frontend/templates/_helpers.tpl
charts/poc-frontend/templates/_required.tpl
charts/poc-frontend/templates/deployment.yaml
charts/poc-frontend/templates/hpa.yaml
charts/poc-frontend/templates/ingressroute.yaml
charts/poc-frontend/templates/service.yaml
charts/poc-frontend/templates/serviceaccount.yaml
charts/poc-frontend/values.yaml

add poc-frontend helm chart for PoC
* [KDOG-58](https://htw-cloud.atlassian.net/browse/KDOG-58)
[KDOG-58]: https://htw-cloud.atlassian.net/browse/KDOG-58?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KDOG-58 add poc-frontend helm chart

---

charts/anaheim-baseline/.helmignore
charts/anaheim-baseline/Chart.yaml
charts/anaheim-baseline/templates/_helpers.tpl
charts/anaheim-baseline/templates/aws-configmap.yaml
charts/anaheim-baseline/templates/dashboard-middleware.yaml
charts/anaheim-baseline/templates/dashboard-secret.yaml
charts/anaheim-baseline/templates/dashboard-traefik.yaml
charts/anaheim-baseline/values.yaml
charts/anaheim-project-service/.helmignore
charts/anaheim-project-service/Chart.yaml
charts/anaheim-project-service/templates/NOTES.txt
charts/anaheim-project-service/templates/_helpers.tpl
charts/anaheim-project-service/templates/_required.tpl
charts/anaheim-project-service/templates/deployment.yaml
charts/anaheim-project-service/templates/hpa.yaml
charts/anaheim-project-service/templates/service.yaml
charts/anaheim-project-service/templates/serviceaccount.yaml
charts/anaheim-project-service/values.yaml

* [DEVO-1055](https://htw-cloud.atlassian.net/browse/DEVO-1055)
* [DEVO-1051](https://htw-cloud.atlassian.net/browse/DEVO-1051)
[DEVO-1055]: https://htw-cloud.atlassian.net/browse/DEVO-1055?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEVO-1051]: https://htw-cloud.atlassian.net/browse/DEVO-1051?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Devo 1055 devo 1051

---

charts/anaheim-training-assets-service/.helmignore
charts/anaheim-training-assets-service/Chart.yaml
charts/anaheim-training-assets-service/templates/NOTES.txt
charts/anaheim-training-assets-service/templates/_helpers.tpl
charts/anaheim-training-assets-service/templates/_required.tpl
charts/anaheim-training-assets-service/templates/deployment.yaml
charts/anaheim-training-assets-service/templates/hpa.yaml
charts/anaheim-training-assets-service/templates/service.yaml
charts/anaheim-training-assets-service/templates/serviceaccount.yaml
charts/anaheim-training-assets-service/values.yaml

devo-1052: helm chart for anaheim-training-assets-service

---

charts/anaheim-annotator-service/.helmignore
charts/anaheim-annotator-service/Chart.yaml
charts/anaheim-annotator-service/templates/NOTES.txt
charts/anaheim-annotator-service/templates/_helpers.tpl
charts/anaheim-annotator-service/templates/_required.tpl
charts/anaheim-annotator-service/templates/deployment.yaml
charts/anaheim-annotator-service/templates/hpa.yaml
charts/anaheim-annotator-service/templates/service.yaml
charts/anaheim-annotator-service/templates/serviceaccount.yaml
charts/anaheim-annotator-service/values.yaml

devo-1053:helm chart for anaheim-annotator-service

---

charts/hasura/charts/anaheim-authentication-service/Chart.yaml
charts/hasura/charts/anaheim-authentication-service/templates/_helpers.tpl
charts/hasura/charts/anaheim-authentication-service/templates/deployment.yaml
charts/hasura/charts/anaheim-authentication-service/templates/ingressroute.yaml
charts/hasura/charts/anaheim-authentication-service/templates/middleware.yaml
charts/hasura/charts/anaheim-authentication-service/templates/service.yaml
charts/hasura/charts/anaheim-authentication-service/templates/serviceaccount.yaml
charts/hasura/charts/anaheim-authentication-service/values.yaml
charts/hasura/values.yaml

devo-1061:added new graphql and auth-service for anaheim

---

charts/cloud-baseline/values.yaml

* [KDOG-172](https://htw-cloud.atlassian.net/browse/KDOG-172)
[KDOG-172]: https://htw-cloud.atlassian.net/browse/KDOG-172?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KDOG-172 update traefik web port 80 to 8080

---

charts/anaheim-project-service/Chart.yaml
charts/anaheim-project-service/templates/ingressroute.yaml
charts/anaheim-project-service/templates/middleware.yaml
charts/anaheim-project-service/values.yaml

added ingress for project service

---

charts/anaheim-baseline/Chart.yaml
charts/anaheim-baseline/values.yaml
charts/anaheim-training-assets-service/Chart.yaml
charts/anaheim-training-assets-service/templates/aws-configmap.yaml
charts/anaheim-training-assets-service/templates/ingressroute.yaml
charts/anaheim-training-assets-service/templates/middleware.yaml
charts/anaheim-training-assets-service/templates/pv.yaml
charts/anaheim-training-assets-service/templates/pvc.yaml
charts/anaheim-training-assets-service/values.yaml

DEVO-1052:helm charts for asset service

---

charts/anaheim-training-assets-service/Chart.yaml
charts/anaheim-training-assets-service/templates/deployment.yaml
charts/anaheim-training-assets-service/templates/pv.yaml
charts/anaheim-training-assets-service/templates/pvc.yaml
charts/anaheim-training-assets-service/values.yaml

fix volume mount

---

charts/anaheim-annotator-service/Chart.yaml
charts/anaheim-annotator-service/templates/deployment.yaml
charts/anaheim-annotator-service/values.yaml
charts/anaheim-project-service/Chart.yaml
charts/anaheim-project-service/values.yaml
charts/anaheim-training-assets-service/Chart.yaml
charts/anaheim-training-assets-service/values.yaml

fix configurations

---

charts/hasura/templates/deployment.yaml

* [DEVO-1086](https://htw-cloud.atlassian.net/browse/DEVO-1086)
[DEVO-1086]: https://htw-cloud.atlassian.net/browse/DEVO-1086?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: update labels with date to force rerun

---

charts/poc-frontend/Chart.yaml

* [KDOG-189](https://htw-cloud.atlassian.net/browse/KDOG-189)
[KDOG-189]: https://htw-cloud.atlassian.net/browse/KDOG-189?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KDOG-189 update version of poc-frontend chart

---

charts/anaheim-portal/templates/ingressroute-training.yaml
charts/anaheim-portal/templates/ingressroute-verify.yaml

Devo 1106 fix

---

charts/anaheim-portal/Chart.yaml

version bump

---

charts/anaheim-portal/Chart.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/values.yaml
charts/anaheim-portal/charts/anaheim-verification-portlet/values.yaml

Anaheim portal 3dks test

---

charts/anaheim-annotator-service/Chart.yaml
charts/anaheim-annotator-service/templates/ingressroute.yaml
charts/anaheim-annotator-service/templates/middleware.yaml
charts/anaheim-annotator-service/values.yaml

chore: add ingress route

---

charts/anaheim-portal/Chart.yaml
charts/anaheim-portal/templates/portal-params.yaml

Add vite environment variable for annotations service integration

chore: add vite annotator api url to env variables

---

charts/anaheim-baseline/Chart.yaml
charts/anaheim-baseline/templates/aws-eventbridge-secret.yaml
charts/anaheim-baseline/values.yaml

chore: update baseline secret

---

charts/anaheim-project-service/Chart.yaml
charts/anaheim-project-service/values.yaml

* [ECHO-326](https://htw-cloud.atlassian.net/browse/ECHO-326)
[ECHO-326]: https://htw-cloud.atlassian.net/browse/ECHO-326?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: add training assets env variable

---

charts/anaheim-eventbridge/.helmignore
charts/anaheim-eventbridge/Chart.yaml
charts/anaheim-eventbridge/templates/NOTES.txt
charts/anaheim-eventbridge/templates/_helpers.tpl
charts/anaheim-eventbridge/templates/_required.tpl
charts/anaheim-eventbridge/templates/deployment.yaml
charts/anaheim-eventbridge/templates/hpa.yaml
charts/anaheim-eventbridge/templates/ingressroute.yaml
charts/anaheim-eventbridge/templates/middleware.yaml
charts/anaheim-eventbridge/templates/service.yaml
charts/anaheim-eventbridge/templates/serviceaccount.yaml
charts/anaheim-eventbridge/values.yaml

feat: add helm chart for eventbridge

---

charts/anaheim-baseline/Chart.yaml
charts/anaheim-baseline/templates/aws-configmap.yaml
charts/anaheim-baseline/templates/aws-eventbridge-secret.yaml

Devo 1141 for realz

---

charts/anaheim-portal/charts/anaheim-container/Chart.yaml
charts/anaheim-portal/charts/anaheim-container/values.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/Chart.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/values.yaml
charts/anaheim-portal/charts/anaheim-verification-portlet/Chart.yaml
charts/anaheim-portal/charts/anaheim-verification-portlet/values.yaml

Add env variables for graphql service on portal
* [LOKI-341](https://htw-cloud.atlassian.net/browse/LOKI-341)
[LOKI-341]: https://htw-cloud.atlassian.net/browse/LOKI-341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: add env variables for graphql service on portal

---

charts/anaheim-annotator-service/Chart.yaml
charts/anaheim-annotator-service/values.yaml

Add env variable for projects service on Annotation service
* [LOKI-355](https://htw-cloud.atlassian.net/browse/LOKI-355)
[LOKI-355]: https://htw-cloud.atlassian.net/browse/LOKI-355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: add env variable for projects service on Annotation service

---

charts/anaheim-project-service/Chart.yaml
charts/anaheim-project-service/values.yaml

Add annotation service url to project service env variables
* [ECHO-302](https://htw-cloud.atlassian.net/browse/ECHO-302)
[ECHO-302]: https://htw-cloud.atlassian.net/browse/ECHO-302?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feature/echo 302/create annotation object class

---

charts/anaheim-portal/Chart.yaml
charts/anaheim-portal/charts/anaheim-container/Chart.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/Chart.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/values.yaml
charts/anaheim-portal/charts/anaheim-verification-portlet/Chart.yaml
charts/anaheim-portal/values.yaml

* [LOKI-412](https://htw-cloud.atlassian.net/browse/LOKI-412)

[LOKI-412] Anaheim Portal initial values

---

charts/anaheim-project-service/Chart.yaml
charts/anaheim-project-service/templates/deployment.yaml
charts/anaheim-project-service/values.yaml

chore: hard code envfrom values

---

charts/anaheim-annotator-service/Chart.yaml
charts/anaheim-annotator-service/templates/deployment.yaml
charts/anaheim-training-assets-service/templates/deployment.yaml
charts/anaheim-training-assets-service/values.yaml

fix: helm charts

---

charts/anaheim-portal/Chart.yaml
charts/anaheim-portal/charts/anaheim-container/Chart.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/Chart.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/values.yaml
charts/anaheim-portal/charts/anaheim-verification-portlet/Chart.yaml
charts/anaheim-portal/values.yaml

* [LOKI-412](https://htw-cloud.atlassian.net/browse/LOKI-412)

[LOKI-412] reset env values

---

charts/anaheim-wavesync-adapter-service/.helmignore
charts/anaheim-wavesync-adapter-service/Chart.yaml
charts/anaheim-wavesync-adapter-service/templates/NOTES.txt
charts/anaheim-wavesync-adapter-service/templates/_helpers.tpl
charts/anaheim-wavesync-adapter-service/templates/_required.tpl
charts/anaheim-wavesync-adapter-service/templates/deployment.yaml
charts/anaheim-wavesync-adapter-service/templates/hpa.yaml
charts/anaheim-wavesync-adapter-service/templates/ingressroute.yaml
charts/anaheim-wavesync-adapter-service/templates/middleware.yaml
charts/anaheim-wavesync-adapter-service/templates/service.yaml
charts/anaheim-wavesync-adapter-service/templates/serviceaccount.yaml
charts/anaheim-wavesync-adapter-service/values.yaml

Created files for WaveSync Adapter service
* [LOKI-651](https://hanwhavision.atlassian.net/browse/LOKI-651)

feat: add helm charts for wavesync-adapter-service

---

charts/anaheim-wavesync-adapter-service/Chart.yaml
charts/anaheim-wavesync-adapter-service/templates/deployment.yaml

fix: removed unnecessary volumes

---

charts/anaheim-wavesync-adapter-service/Chart.yaml
charts/anaheim-wavesync-adapter-service/values.yaml

Added WAVESYNC_BASE_URL env variable
* [LOKI659](https://hanwhavision.atlassian.net/browse/LOKI-659)

[LOKI-659] Helm chart create needed env variables

---

charts/anaheim-wavesync-adapter-service/Chart.yaml
charts/anaheim-wavesync-adapter-service/values.yaml

[](fix: updated wavesync base url to string)

fix: updated wavesync base url to string

---

charts/anaheim-feature-flags-service/.helmignore
charts/anaheim-feature-flags-service/Chart.yaml
charts/anaheim-feature-flags-service/templates/NOTES.txt
charts/anaheim-feature-flags-service/templates/_helpers.tpl
charts/anaheim-feature-flags-service/templates/_required.tpl
charts/anaheim-feature-flags-service/templates/deployment.yaml
charts/anaheim-feature-flags-service/templates/hpa.yaml
charts/anaheim-feature-flags-service/templates/ingressroute.yaml
charts/anaheim-feature-flags-service/templates/middleware.yaml
charts/anaheim-feature-flags-service/templates/service.yaml
charts/anaheim-feature-flags-service/templates/serviceaccount.yaml
charts/anaheim-feature-flags-service/values.yaml

Add FF service helm chart
* [LOKI-548](https://htw-cloud.atlassian.net/browse/LOKI-548)

chore: add FF service helm chart

---

charts/anaheim-wavesync-adapter-service/Chart.yaml
charts/anaheim-wavesync-adapter-service/values.yaml

Added WAVESYNC_BOOKMARKS_URL
* [LOKI-789](https://hanwhavision.atlassian.net/browse/LOKI-789)

[LOKI-789] - Create variable on helm charts for get bookmarks URL on WaveSync service

---

charts/anaheim-portal/Chart.yaml
charts/anaheim-portal/values.yaml

Fix helm values

---

charts/anaheim-wavesync-adapter-service/Chart.yaml
charts/anaheim-wavesync-adapter-service/values.yaml

Adding ASSET SERVICE URL environment variable to wavesync service

---

charts/anaheim-portal/templates/portal-params.yaml

Add wavesync vite config to portal
* [AN-830](https://htw-cloud.atlassian.net/browse/AN-830)

chore: add wavesync vite config to portal

---

charts/anaheim-portal/Chart.yaml
charts/anaheim-portal/charts/anaheim-container/Chart.yaml
charts/anaheim-portal/charts/anaheim-container/values.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/Chart.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/values.yaml
charts/anaheim-portal/charts/anaheim-verification-portlet/Chart.yaml
charts/anaheim-portal/charts/anaheim-verification-portlet/values.yaml
charts/anaheim-portal/values.yaml

fix: add more memory to portal

---

charts/anaheim-wavesync-adapter-service/Chart.yaml
charts/anaheim-wavesync-adapter-service/values.yaml

Created NODE_ENV environment variable
* [AN-835](https://hanwhavision.atlassian.net/browse/AN-835)

[AN-835] Create env variable on helm charts

---

charts/anaheim-annotator-service/Chart.yaml
charts/anaheim-annotator-service/templates/deployment.yaml
charts/anaheim-annotator-service/values.yaml
charts/anaheim-eventbridge/Chart.yaml
charts/anaheim-eventbridge/templates/deployment.yaml
charts/anaheim-training-assets-service/Chart.yaml
charts/anaheim-training-assets-service/templates/deployment.yaml
charts/anaheim-training-assets-service/values.yaml

Enable liveness & readiness checks

---

charts/anaheim-portal/Chart.yaml
charts/anaheim-portal/templates/portal-params.yaml

Added VITE_AUTH_API env variable
* [AN-977](https://hanwhavision.atlassian.net/browse/AN-977)

Create VITE_AUTH_API env on helm charts for Portal

---

charts/anaheim-baseline/templates/duclo-configmap.yaml
charts/anaheim-baseline/values.yaml
charts/hasura/Chart.yaml
charts/hasura/charts/anaheim-authentication-service/Chart.yaml
charts/hasura/charts/anaheim-authentication-service/templates/deployment.yaml
charts/hasura/templates/deployment.yaml

DEVO-1386 : corrected configurations

---

charts/anaheim-wavesync-adapter-service/Chart.yaml
charts/anaheim-wavesync-adapter-service/values.yaml

add encryption key

---

charts/anaheim-gatekeeper-service/.helmignore
charts/anaheim-gatekeeper-service/Chart.yaml
charts/anaheim-gatekeeper-service/templates/NOTES.txt
charts/anaheim-gatekeeper-service/templates/_helpers.tpl
charts/anaheim-gatekeeper-service/templates/_required.tpl
charts/anaheim-gatekeeper-service/templates/auth-middleware.yaml
charts/anaheim-gatekeeper-service/templates/deployment.yaml
charts/anaheim-gatekeeper-service/templates/hpa.yaml
charts/anaheim-gatekeeper-service/templates/ingressroute.yaml
charts/anaheim-gatekeeper-service/templates/middleware.yaml
charts/anaheim-gatekeeper-service/templates/service.yaml
charts/anaheim-gatekeeper-service/templates/serviceaccount.yaml
charts/anaheim-gatekeeper-service/values.yaml

add gatekeeper helm chart

---

charts/anaheim-baseline/Chart.yaml
charts/anaheim-baseline/templates/wavesync-token.yaml
charts/anaheim-baseline/values.yaml

add fix wavesync

---

charts/anaheim-wavesync-adapter-service/Chart.yaml
charts/anaheim-wavesync-adapter-service/templates/deployment.yaml

fix wavesync vars

---

charts/anaheim-wavesync-adapter-service/Chart.yaml
charts/anaheim-wavesync-adapter-service/values.yaml

remove hard code

---

.gitignore
charts/anaheim-ai-boxify-service/.helmignore
charts/anaheim-ai-boxify-service/Chart.yaml
charts/anaheim-ai-boxify-service/templates/NOTES.txt
charts/anaheim-ai-boxify-service/templates/_helpers.tpl
charts/anaheim-ai-boxify-service/templates/_required.tpl
charts/anaheim-ai-boxify-service/templates/deployment.yaml
charts/anaheim-ai-boxify-service/templates/hpa.yaml
charts/anaheim-ai-boxify-service/templates/ingressroute.yaml
charts/anaheim-ai-boxify-service/templates/middleware.yaml
charts/anaheim-ai-boxify-service/templates/service.yaml
charts/anaheim-ai-boxify-service/templates/serviceaccount.yaml
charts/anaheim-ai-boxify-service/values.yaml
charts/anaheim-baseline/templates/aws-configmap.yaml
charts/anaheim-baseline/values.yaml

completed helm part for boxify

---

.gitignore
charts/anaheim-ai-boxify-service/Chart.yaml
charts/anaheim-ai-boxify-service/templates/deployment.yaml

secrets removed for boxify

---

charts/anaheim-ai-boxify-service/Chart.yaml
charts/anaheim-ai-boxify-service/values.yaml

Anaheim ai boxify service (Increase CPU & Memory, fix heath endpoints).

---

charts/anaheim-portal/Chart.yaml
charts/anaheim-portal/charts/anaheim-container/Chart.yaml
charts/anaheim-portal/charts/anaheim-container/templates/ingressroute.yaml
charts/anaheim-portal/charts/anaheim-container/templates/middleware.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/Chart.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/templates/ingressroute.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/templates/middleware.yaml
charts/anaheim-training-assets-service/values.yaml

DEVO-1447 added routes

---

charts/anaheim-ai-boxify-service/Chart.yaml
charts/anaheim-ai-boxify-service/values.yaml

Increase CPU resource for the boxify service

---

charts/anaheim-ai-boxify-service/Chart.yaml
charts/anaheim-ai-boxify-service/values.yaml

devo-1494 - use 2 cores

---

charts/anaheim-project-service/templates/ingressroute.yaml

DEVO-1495: changing ingress route priority

---

charts/anaheim-ai-boxify-service/Chart.yaml
charts/anaheim-portal/Chart.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/Chart.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/templates/ingressroute.yaml

DEVO-1498: Change priority for training

---

charts/anaheim-ai-boxify-service/Chart.yaml
charts/anaheim-ai-boxify-service/templates/deployment.yaml

remove livenessProbe and readinessProbe

---

charts/anaheim-baseline/templates/aws-configmap.yaml

DEVO-1518: Add boxify environment variable

---

charts/anaheim-wavesync-adapter-service/values.yaml

DEVO-1519: added FEATURE_FLAGS_API_URL to wavesync

---

charts/anaheim-portal/charts/anaheim-training-portlet/templates/ingressroute.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/templates/middleware.yaml

DEVO-1521: adding /project:id as path

---

charts/anaheim-portal/Chart.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/Chart.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/templates/ingressroute.yaml

DEVO-1521: fixing portal routes

---

charts/anaheim-portal/charts/anaheim-container/Chart.yaml
charts/anaheim-portal/charts/anaheim-container/values.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/Chart.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/values.yaml
charts/anaheim-portal/charts/anaheim-verification-portlet/Chart.yaml
charts/anaheim-portal/charts/anaheim-verification-portlet/values.yaml
charts/anaheim-portal/values.yaml

DEVO-1537: changing replicaCount to 3 in Portal

---

charts/anaheim-portal/Chart.yaml
charts/anaheim-portal/charts/anaheim-container/templates/ingressroute.yaml
charts/anaheim-portal/charts/anaheim-container/templates/middleware.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/templates/ingressroute.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/templates/middleware.yaml

DEVO-1521: changing routes for portal

---

charts/anaheim-ai-boxify-service/Chart.yaml
charts/anaheim-ai-boxify-service/templates/deployment.yaml
charts/anaheim-ai-boxify-service/values.yaml
charts/anaheim-wavesync-adapter-service/Chart.yaml
charts/anaheim-wavesync-adapter-service/templates/deployment.yaml
charts/anaheim-wavesync-adapter-service/values.yaml

DEVO-1538:Boxify on EKS

---

charts/anaheim-ai-boxify-service/Chart.yaml
charts/anaheim-ai-boxify-service/values.yaml
charts/anaheim-annotator-service/Chart.yaml
charts/anaheim-annotator-service/values.yaml
charts/anaheim-eventbridge/Chart.yaml
charts/anaheim-eventbridge/values.yaml
charts/anaheim-feature-flags-service/Chart.yaml
charts/anaheim-feature-flags-service/values.yaml
charts/anaheim-gatekeeper-service/Chart.yaml
charts/anaheim-gatekeeper-service/values.yaml
charts/anaheim-portal/values.yaml
charts/anaheim-project-service/Chart.yaml
charts/anaheim-project-service/values.yaml
charts/anaheim-training-assets-service/Chart.yaml
charts/anaheim-training-assets-service/values.yaml
charts/anaheim-wavesync-adapter-service/Chart.yaml
charts/anaheim-wavesync-adapter-service/values.yaml

DEVO-1530: enabling autoscaling

---

charts/anaheim-ai-boxify-service/Chart.yaml
charts/anaheim-ai-boxify-service/values.yaml
charts/anaheim-annotator-service/Chart.yaml
charts/anaheim-annotator-service/values.yaml
charts/anaheim-eventbridge/Chart.yaml
charts/anaheim-eventbridge/values.yaml
charts/anaheim-feature-flags-service/Chart.yaml
charts/anaheim-feature-flags-service/values.yaml
charts/anaheim-project-service/Chart.yaml
charts/anaheim-project-service/values.yaml
charts/anaheim-training-assets-service/Chart.yaml
charts/anaheim-training-assets-service/values.yaml
charts/anaheim-wavesync-adapter-service/Chart.yaml
charts/anaheim-wavesync-adapter-service/values.yaml

disabling autoscaling

---

charts/anaheim-portal/charts/anaheim-container/templates/ingressroutes.yaml

DEVO-1521: adding routes in portal container

---

charts/anaheim-licensing-adapter/.helmignore
charts/anaheim-licensing-adapter/Chart.yaml
charts/anaheim-licensing-adapter/templates/NOTES.txt
charts/anaheim-licensing-adapter/templates/_helpers.tpl
charts/anaheim-licensing-adapter/templates/_required.tpl
charts/anaheim-licensing-adapter/templates/auth-middleware.yaml
charts/anaheim-licensing-adapter/templates/deployment.yaml
charts/anaheim-licensing-adapter/templates/hpa.yaml
charts/anaheim-licensing-adapter/templates/ingressroute.yaml
charts/anaheim-licensing-adapter/templates/middleware.yaml
charts/anaheim-licensing-adapter/templates/service.yaml
charts/anaheim-licensing-adapter/templates/serviceaccount.yaml

DEVO-1559: adding chart for licensing adapter

---

charts/anaheim-portal/charts/anaheim-container/values.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/values.yaml
charts/anaheim-portal/charts/anaheim-verification-portlet/values.yaml
charts/anaheim-portal/values.yaml

remove replica set

---

charts/anaheim-licensing-adapter/values.yaml

DEVO-1559: changing values in licensing adapter

---

charts/anaheim-portal/charts/anaheim-container/templates/ingressroute.yaml
charts/anaheim-portal/charts/anaheim-container/templates/ingressroutes.yaml

DEVO-1521: changing routes in portal

---

charts/anaheim-licensing-adapter/templates/deployment.yaml
charts/anaheim-licensing-adapter/values.yaml

DEVO-1530: adding autoscaling in licensing-adapter

---

charts/anaheim-portal/templates/app-service-env.yaml
charts/anaheim-portal/values.yaml

test env values addeded to meta data

---

charts/anaheim-portal/Chart.yaml

update chart version

---

charts/anaheim-licensing-adapter/Chart.yaml
charts/anaheim-licensing-adapter/templates/chain-middleware.yaml
charts/anaheim-licensing-adapter/templates/deployment.yaml
charts/anaheim-licensing-adapter/templates/hpa.yaml
charts/anaheim-licensing-adapter/templates/ingressroute.yaml
charts/anaheim-licensing-adapter/templates/license-validate-middleware.yaml
charts/anaheim-licensing-adapter/values.yaml
charts/anaheim-portal/Chart.yaml
charts/anaheim-portal/charts/anaheim-container/Chart.yaml
charts/anaheim-portal/charts/anaheim-container/templates/ingressroutes.yaml
charts/anaheim-portal/charts/anaheim-container/templates/middleware.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/Chart.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/templates/ingressroute.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/templates/middleware.yaml

Devo 1556 chain routing

---

charts/anaheim-portal/values.yaml

fix error in pointer

---

charts/anaheim-portal/Chart.yaml

bump chart version

---

charts/anaheim-portal/values.yaml

disable autoscaling

---

charts/anaheim-portal/Chart.yaml
charts/anaheim-portal/charts/anaheim-container/Chart.yaml
charts/anaheim-portal/charts/anaheim-container/templates/ingressroutes.yaml
charts/anaheim-portal/charts/anaheim-container/templates/middleware.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/Chart.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/templates/ingressroute.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/templates/middleware.yaml

changes in portal

---

charts/anaheim-portal/charts/anaheim-container/templates/ingressroutes.yaml

fix routes

---

charts/anaheim-portal/charts/anaheim-container/templates/ingressroutes.yaml
charts/anaheim-portal/charts/anaheim-container/templates/middleware.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/templates/ingressroute.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/templates/middleware.yaml

reverting changes

---

charts/anaheim-portal/Chart.yaml
charts/anaheim-portal/charts/anaheim-container/Chart.yaml
charts/anaheim-portal/charts/anaheim-container/templates/middleware.yaml

DEVO-1581: redirecting /help path

---

charts/anaheim-portal/Chart.yaml
charts/anaheim-portal/charts/anaheim-container/Chart.yaml
charts/anaheim-portal/charts/anaheim-container/templates/middleware.yaml

DEVO-1581: changes in /help route

---

charts/anaheim-licensing-adapter/Chart.yaml
charts/anaheim-licensing-adapter/templates/deployment.yaml

DEVO-1597: add authentication hostname variable to licensing adapter

---

charts/anaheim-portal/Chart.yaml
charts/anaheim-portal/charts/anaheim-container/Chart.yaml
charts/anaheim-portal/charts/anaheim-container/templates/middleware.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/Chart.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/templates/ingressroute.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/templates/middleware.yaml

DEVO-1581: changes in /help

---

charts/hasura/Chart.yaml
charts/hasura/templates/deployment.yaml
charts/hasura/values.yaml

fix deployment

---

charts/anaheim-portal/charts/anaheim-container/templates/ingressroutes.yaml

Added routes for license

---

charts/anaheim-portal/charts/anaheim-container/Chart.yaml
charts/anaheim-portal/charts/anaheim-container/templates/ingressroutes.yaml
charts/anaheim-portal/charts/anaheim-container/templates/middleware.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/Chart.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/templates/ingressroute.yaml

devo-1582: fixed routes and validate with david

---

charts/anaheim-project-service/templates/chain-middleware.yaml
charts/anaheim-project-service/templates/ingressroute.yaml
charts/anaheim-project-service/templates/license-validate-middleware.yaml
charts/anaheim-project-service/values.yaml

1589-Added helm chart for chain and license-validate middleware

---

charts/hasura/Chart.yaml
charts/hasura/values.yaml

add env var

---

charts/anaheim-ai-boxify-service/Chart.yaml
charts/anaheim-ai-boxify-service/templates/chain-middleware.yaml
charts/anaheim-ai-boxify-service/templates/ingressroute.yaml
charts/anaheim-ai-boxify-service/templates/license-validate-middleware.yaml
charts/anaheim-ai-boxify-service/values.yaml
charts/anaheim-annotator-service/Chart.yaml
charts/anaheim-annotator-service/templates/chain-middleware.yaml
charts/anaheim-annotator-service/templates/ingressroute.yaml
charts/anaheim-annotator-service/templates/license-validate-middleware.yaml
charts/anaheim-annotator-service/values.yaml
charts/anaheim-feature-flags-service/Chart.yaml
charts/anaheim-feature-flags-service/templates/chain-middleware.yaml
charts/anaheim-feature-flags-service/templates/ingressroute.yaml
charts/anaheim-feature-flags-service/templates/license-validate-middleware.yaml
charts/anaheim-feature-flags-service/values.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/Chart.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/templates/chain-middleware.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/templates/ingressroute.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/templates/license-validate-middleware.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/values.yaml
charts/anaheim-training-assets-service/Chart.yaml
charts/anaheim-training-assets-service/templates/chain-middleware.yaml
charts/anaheim-training-assets-service/templates/ingressroute.yaml
charts/anaheim-training-assets-service/templates/license-validate-middleware.yaml
charts/anaheim-training-assets-service/values.yaml

Added all chain and license middleware

---

charts/anaheim-licensing-adapter/templates/deployment.yaml

Added partner in the env

---

charts/anaheim-project-service/values.yaml
charts/anaheim-training-assets-service/Chart.yaml
charts/anaheim-training-assets-service/templates/chain-middleware.yaml
charts/anaheim-training-assets-service/templates/license-validate-middleware.yaml

Fix assets routes

---

charts/anaheim-baseline/templates/duclo-configmap.yaml
charts/anaheim-licensing-adapter/Chart.yaml

add license url

---

charts/anaheim-portal/Chart.yaml
charts/anaheim-portal/charts/anaheim-container/Chart.yaml
charts/anaheim-portal/charts/anaheim-container/templates/ingressroutes.yaml
charts/anaheim-portal/charts/anaheim-container/templates/middleware.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/Chart.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/values.yaml
charts/anaheim-portal/charts/anaheim-verification-portlet/Chart.yaml
charts/anaheim-portal/templates/portal-params.yaml
charts/anaheim-portal/values.yaml

Devo 1605 - Training route fix 

---

charts/anaheim-feature-flags-service/templates/ingressroute.yaml

Reverted chain middle

---

charts/anaheim-feature-flags-service/templates/ingressroute.yaml

Removed chain middleware

---

charts/anaheim-portal/Chart.yaml
charts/anaheim-portal/charts/anaheim-container/templates/ingressroutes.yaml
charts/anaheim-portal/charts/anaheim-container/templates/middleware.yaml

Devo 1581 2

---

charts/anaheim-portal/Chart.yaml
charts/anaheim-portal/charts/anaheim-container/Chart.yaml

updated helm version

---

charts/anaheim-ai-boxify-service/Chart.yaml
charts/anaheim-ai-boxify-service/templates/deployment.yaml
charts/anaheim-ai-boxify-service/templates/hpa.yaml
charts/anaheim-ai-boxify-service/values.yaml
charts/anaheim-annotator-service/Chart.yaml
charts/anaheim-annotator-service/templates/deployment.yaml
charts/anaheim-annotator-service/templates/hpa.yaml
charts/anaheim-annotator-service/values.yaml
charts/anaheim-eventbridge/Chart.yaml
charts/anaheim-eventbridge/templates/deployment.yaml
charts/anaheim-eventbridge/templates/hpa.yaml
charts/anaheim-eventbridge/values.yaml
charts/anaheim-feature-flags-service/Chart.yaml
charts/anaheim-feature-flags-service/templates/deployment.yaml
charts/anaheim-feature-flags-service/templates/hpa.yaml
charts/anaheim-feature-flags-service/values.yaml
charts/anaheim-licensing-adapter/templates/hpa.yaml
charts/anaheim-licensing-adapter/values.yaml
charts/anaheim-project-service/templates/hpa.yaml
charts/anaheim-project-service/values.yaml
charts/anaheim-training-assets-service/Chart.yaml
charts/anaheim-training-assets-service/templates/deployment.yaml
charts/anaheim-training-assets-service/values.yaml
charts/anaheim-wavesync-adapter-service/Chart.yaml
charts/anaheim-wavesync-adapter-service/templates/deployment.yaml
charts/anaheim-wavesync-adapter-service/templates/hpa.yaml
charts/anaheim-wavesync-adapter-service/values.yaml

DEVO-1530: adding changes for autoscaling

---

charts/anaheim-licensing-adapter/Chart.yaml
charts/anaheim-licensing-adapter/templates/deployment.yaml

DEVO-1628: Added duclo key for licensing adapter

---

charts/anaheim-annotator-service/Chart.yaml
charts/anaheim-annotator-service/templates/ingressroute.yaml
charts/anaheim-project-service/Chart.yaml
charts/anaheim-project-service/templates/ingressroute.yaml
charts/anaheim-wavesync-adapter-service/Chart.yaml
charts/anaheim-wavesync-adapter-service/templates/ingressroute.yaml

Added routes

---

charts/anaheim-annotator-service/templates/ingressroute.yaml

Added correct value

---

charts/anaheim-project-service/values.yaml

DEVO-1634: adding new variable in project-service

---

charts/anaheim-project-service/Chart.yaml

DEVO-1634: bumping up version for project-service

---

charts/anaheim-project-service/values.yaml

DEVO-1634: dummy deploy

---

charts/anaheim-annotator-service/Chart.yaml
charts/anaheim-annotator-service/templates/ingressroute.yaml
charts/anaheim-project-service/Chart.yaml
charts/anaheim-project-service/templates/ingressroute.yaml
charts/anaheim-wavesync-adapter-service/Chart.yaml
charts/anaheim-wavesync-adapter-service/templates/ingressroute.yaml

Added additional-midlleware

---

charts/hasura/Chart.yaml
charts/hasura/templates/deployment.yaml

Added enabled flag

---

charts/anaheim-ai-boxify-service/Chart.yaml
charts/anaheim-ai-boxify-service/values.yaml
charts/anaheim-annotator-service/Chart.yaml
charts/anaheim-annotator-service/values.yaml
charts/anaheim-feature-flags-service/Chart.yaml
charts/anaheim-feature-flags-service/values.yaml
charts/anaheim-licensing-adapter/Chart.yaml
charts/anaheim-licensing-adapter/values.yaml
charts/anaheim-project-service/Chart.yaml
charts/anaheim-project-service/values.yaml
charts/anaheim-training-assets-service/Chart.yaml
charts/anaheim-training-assets-service/values.yaml
charts/anaheim-wavesync-adapter-service/Chart.yaml
charts/anaheim-wavesync-adapter-service/values.yaml

Reverted topology and affinity

---

charts/anaheim-training-assets-service/templates/hpa.yaml

Added correct version of hpa

---

charts/hasura/Chart.yaml
charts/hasura/templates/deployment.yaml

Fix hasura console

---

charts/anaheim-training-assets-service/Chart.yaml
charts/anaheim-training-assets-service/templates/hpa.yaml

Fixed hpa Training Assets

---

charts/anaheim-portal/Chart.yaml
charts/anaheim-portal/charts/anaheim-container/Chart.yaml
charts/anaheim-portal/charts/anaheim-container/templates/deployment.yaml
charts/anaheim-portal/charts/anaheim-container/templates/hpa.yaml
charts/anaheim-portal/charts/anaheim-container/values.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/Chart.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/templates/deployment.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/templates/hpa.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/values.yaml
charts/anaheim-portal/charts/anaheim-verification-portlet/Chart.yaml
charts/anaheim-portal/charts/anaheim-verification-portlet/templates/deployment.yaml
charts/anaheim-portal/charts/anaheim-verification-portlet/templates/hpa.yaml
charts/anaheim-portal/charts/anaheim-verification-portlet/values.yaml

DEVO-1530: adding scaling for portal

---

charts/anaheim-portal/charts/anaheim-container/templates/deployment.yaml
charts/anaheim-portal/charts/anaheim-container/values.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/templates/deployment.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/values.yaml
charts/anaheim-portal/charts/anaheim-verification-portlet/templates/deployment.yaml
charts/anaheim-portal/charts/anaheim-verification-portlet/values.yaml

DEVO-1530: fixing deployment file for portal

---

charts/anaheim-training-assets-service/Chart.yaml
charts/anaheim-training-assets-service/templates/chain-middleware.yaml
charts/anaheim-training-assets-service/templates/ingressroute.yaml

Devo 1643 routes

---

charts/anaheim-portal/charts/anaheim-training-portlet/templates/deployment.yaml

Fix training portlet

---

charts/anaheim-portal/charts/anaheim-container/Chart.yaml
charts/anaheim-portal/charts/anaheim-container/templates/deployment.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/Chart.yaml
charts/anaheim-portal/charts/anaheim-verification-portlet/Chart.yaml
charts/anaheim-portal/charts/anaheim-verification-portlet/templates/deployment.yaml

Added version and fix other portal

---

charts/anaheim-portal/Chart.yaml
charts/hasura/Chart.yaml
charts/hasura/templates/deployment.yaml

Add devo 1629 hasura

---

charts/hasura/templates/deployment.yaml
charts/hasura/values.yaml

Added env to set false if dev and prod

---

charts/anaheim-baseline/values.yaml

added baseline

---

charts/hasura/Chart.yaml
charts/hasura/charts/anaheim-authentication-service/Chart.yaml
charts/hasura/templates/deployment.yaml
charts/hasura/values.yaml

Add graphql devo 1656

---

charts/hasura/templates/deployment.yaml
charts/hasura/values.yaml

Added values

---

charts/anaheim-baseline/Chart.yaml

Added version

---

charts/anaheim-baseline/values.yaml

Added metrics and tracing and accesslogs

---

charts/hasura/Chart.yaml
charts/hasura/templates/deployment.yaml

Added if condition

---

charts/hasura/Chart.yaml
charts/hasura/templates/deployment.yaml

Add value hasura devo 1656

---

charts/anaheim-project-service/values.yaml

DEVO-1667: adding new variable in project-service

---

charts/anaheim-project-service/Chart.yaml

DEVO-1667: bumping up version in project-service chart

---

charts/anaheim-project-service/Chart.yaml
charts/anaheim-project-service/templates/deployment.yaml
charts/anaheim-project-service/values.yaml

Added test

---

charts/hasura/Chart.yaml
charts/hasura/templates/deployment.yaml

Fix console

---

charts/anaheim-portal/charts/anaheim-container/templates/middleware.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/templates/middleware.yaml
charts/anaheim-portal/charts/anaheim-verification-portlet/templates/middleware.yaml

Devo 1686 noindex

---

charts/anaheim-ai-boxify-service/Chart.yaml
charts/anaheim-ai-boxify-service/values.yaml

add env vars for boxify service

---

charts/anaheim-project-service/Chart.yaml
charts/anaheim-project-service/templates/deployment.yaml
charts/datadog/datadog-agent1.yaml

Added vlaues labels

---

charts/anaheim-training-assets-service/Chart.yaml
charts/anaheim-training-assets-service/values.yaml

DEVO-1705: changing mem size in training-assts service

---

charts/anaheim-portal/Chart.yaml
charts/anaheim-portal/charts/anaheim-container/Chart.yaml
charts/anaheim-portal/charts/anaheim-container/values.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/Chart.yaml
charts/anaheim-portal/charts/anaheim-training-portlet/values.yaml
charts/anaheim-portal/charts/anaheim-verification-portlet/Chart.yaml
charts/anaheim-portal/charts/anaheim-verification-portlet/values.yaml
charts/anaheim-portal/values.yaml

devo-1714: fix helm chart

---

charts/anaheim-portal/charts/anaheim-container/Chart.yaml
charts/anaheim-portal/charts/anaheim-container/templates/ingressroute.yaml

Added correct classname

---

charts/anaheim-portal-dev/.helmignore
charts/anaheim-portal-dev/Chart.yaml
charts/anaheim-portal-dev/templates/_helpers.tpl
charts/anaheim-portal-dev/templates/deployment.yaml
charts/anaheim-portal-dev/templates/hpa.yaml
charts/anaheim-portal-dev/templates/ingressroute.yaml
charts/anaheim-portal-dev/templates/ingressroutes.yaml
charts/anaheim-portal-dev/templates/middleware.yaml
charts/anaheim-portal-dev/templates/portal-params.yaml
charts/anaheim-portal-dev/templates/service.yaml
charts/anaheim-portal-dev/templates/serviceaccount.yaml

portal as a single container

---

charts/anaheim-annotator-service/Chart.yaml
charts/anaheim-annotator-service/templates/deployment.yaml
charts/anaheim-feature-flags-service/Chart.yaml
charts/anaheim-feature-flags-service/templates/deployment.yaml
charts/anaheim-licensing-adapter/Chart.yaml
charts/anaheim-licensing-adapter/templates/deployment.yaml
charts/anaheim-portal/Chart.yaml
charts/anaheim-portal/templates/deployment.yaml
charts/anaheim-project-service/Chart.yaml
charts/anaheim-project-service/templates/deployment.yaml
charts/anaheim-training-assets-service/Chart.yaml
charts/anaheim-training-assets-service/templates/deployment.yaml
charts/anaheim-wavesync-adapter-service/Chart.yaml
charts/anaheim-wavesync-adapter-service/templates/deployment.yaml
charts/datadog/datadog-agent1.yaml

Enable tracing devo 1768

---

charts/anaheim-annotator-service/Chart.yaml
charts/anaheim-annotator-service/values.yaml

Reword the env

---

charts/anaheim-ai-boxify-service/Chart.yaml
charts/anaheim-ai-boxify-service/values.yaml
charts/anaheim-feature-flags-service/Chart.yaml
charts/anaheim-feature-flags-service/values.yaml
charts/anaheim-licensing-adapter/Chart.yaml
charts/anaheim-licensing-adapter/values.yaml
charts/anaheim-portal/values.yaml
charts/anaheim-project-service/Chart.yaml
charts/anaheim-project-service/values.yaml
charts/anaheim-training-assets-service/Chart.yaml
charts/anaheim-training-assets-service/values.yaml
charts/anaheim-wavesync-adapter-service/Chart.yaml
charts/anaheim-wavesync-adapter-service/values.yaml

Added unify tag

---

charts/anaheim-ai-boxify-service/values.yaml

DEVO-1725: changed boxify params

---

charts/anaheim-flexai-devices-service/Chart.yaml
charts/anaheim-flexai-devices-service/templates/NOTES.txt
charts/anaheim-flexai-devices-service/templates/_helpers.tpl
charts/anaheim-flexai-devices-service/templates/_required.tpl
charts/anaheim-flexai-devices-service/templates/deployment.yaml
charts/anaheim-flexai-devices-service/templates/hpa.yaml
charts/anaheim-flexai-devices-service/templates/ingressroute.yaml
charts/anaheim-flexai-devices-service/templates/middleware.yaml
charts/anaheim-flexai-devices-service/templates/service.yaml
charts/anaheim-flexai-devices-service/templates/serviceaccount.yaml
charts/anaheim-flexai-devices-service/values.yaml

@davidgc-wisenet , can you please review this PR? We need to check if there something specific for this new service.

DEVO-1829: Created folder for flexai-devices-service

---

charts/anaheim-flexai-devices-service/Chart.yaml
charts/anaheim-flexai-devices-service/templates/deployment.yaml

DEVO-1856: adding variables in flexai-devices

---

charts/anaheim-baseline/templates/datadog-secrets.yaml
charts/anaheim-baseline/values.yaml
charts/anaheim-portal/Chart.yaml
charts/anaheim-portal/templates/deployment.yaml

Added devo 1852

---

charts/anaheim-oncloud-clip-service/Chart.yaml
charts/anaheim-oncloud-clip-service/templates/deployment.yaml

DEVO-1866: adding duclo key variables in oncloud-clip

---

charts/anaheim-feature-flags-service/Chart.yaml
charts/anaheim-feature-flags-service/templates/deployment.yaml
charts/anaheim-flexai-devices-service/Chart.yaml
charts/anaheim-flexai-devices-service/templates/deployment.yaml
charts/anaheim-licensing-adapter/Chart.yaml
charts/anaheim-licensing-adapter/templates/deployment.yaml
charts/anaheim-oncloud-clip-service/Chart.yaml
charts/anaheim-oncloud-clip-service/templates/deployment.yaml
charts/anaheim-portal/Chart.yaml
charts/anaheim-portal/templates/deployment.yaml
charts/anaheim-project-service/Chart.yaml
charts/anaheim-project-service/templates/deployment.yaml
charts/anaheim-training-assets-service/Chart.yaml
charts/anaheim-training-assets-service/templates/deployment.yaml
charts/anaheim-wavesync-adapter-service/Chart.yaml
charts/anaheim-wavesync-adapter-service/templates/deployment.yaml
charts/hasura/charts/anaheim-authentication-service/Chart.yaml
charts/hasura/charts/anaheim-authentication-service/templates/deployment.yaml

Added all app env node

---

charts/hasura/charts/anaheim-authentication-service/Chart.yaml
charts/hasura/charts/anaheim-authentication-service/templates/deployment.yaml

Temp fix devo 1887

---

charts/anaheim-annotator-service/Chart.yaml
charts/anaheim-annotator-service/values.yaml
charts/anaheim-feature-flags-service/Chart.yaml
charts/anaheim-feature-flags-service/values.yaml
charts/anaheim-project-service/Chart.yaml
charts/anaheim-project-service/values.yaml
charts/anaheim-training-assets-service/Chart.yaml
charts/anaheim-training-assets-service/values.yaml

chore: add node env variable for old charts

---

charts/anaheim-licensing-adapter/Chart.yaml
charts/anaheim-licensing-adapter/values.yaml

* https://hanwhavision.atlassian.net/browse/AN-3499

[AN-3499] - Add url project env variable

---

charts/anaheim-licensing-adapter/Chart.yaml
charts/anaheim-licensing-adapter/templates/deployment.yaml

* https://hanwhavision.atlassian.net/browse/AN-3529

[AN-3529]  - Add sqs env variables

---

charts/anaheim-flexai-devices-service/templates/deployment.yaml

feat: add secret to flexai dvice service

---

charts/anaheim-flexai-devices-service/Chart.yaml

feat: add new release

---

charts/anaheim-ai-boxify-service/Chart.yaml
charts/anaheim-ai-boxify-service/_helpers.tpl
charts/anaheim-ai-boxify-service/values.yaml

feat: add origin proxy address

---

charts/anaheim-flexai-devices-service/Chart.yaml
charts/anaheim-flexai-devices-service/templates/deployment.yaml

feat: edit wrong typing

---

charts/anaheim-ai-boxify-service/Chart.yaml
charts/anaheim-ai-boxify-service/templates/_helpers.tpl

feat: add new template

---

charts/anaheim-baseline/templates/aws-sqs-secret.yaml
charts/anaheim-baseline/values.yaml

feat: edit baseline

---

charts/anaheim-job-scheduler/.helmignore
charts/anaheim-job-scheduler/Chart.yaml
charts/anaheim-job-scheduler/templates/NOTES.txt
charts/anaheim-job-scheduler/templates/_helpers.tpl
charts/anaheim-job-scheduler/templates/_required.tpl
charts/anaheim-job-scheduler/templates/deployment.yaml
charts/anaheim-job-scheduler/templates/serviceaccount.yaml
charts/anaheim-job-scheduler/values.yaml

feat: add job scheduler

---

charts/anaheim-job-scheduler/templates/deployment.yaml

feat: edit wrong chart

---

charts/anaheim-job-scheduler/Chart.yaml

feat: Update Chart.yaml

---

charts/anaheim-flexai-devices-service/Chart.yaml
charts/anaheim-flexai-devices-service/templates/serviceaccount.yaml
charts/anaheim-flexai-devices-service/values.yaml

feat: add anotation

---

charts/anaheim-flexai-devices-service/Chart.yaml
charts/anaheim-flexai-devices-service/templates/serviceaccount.yaml
charts/anaheim-flexai-devices-service/values.yaml

Kdog edit helmchart

---

charts/anaheim-project-service/Chart.yaml
charts/anaheim-project-service/templates/deployment.yaml

feat: add db info to project service

---

charts/anaheim-job-scheduler/Chart.yaml
charts/anaheim-job-scheduler/templates/auth-middleware.yaml
charts/anaheim-job-scheduler/templates/chain-middleware.yaml
charts/anaheim-job-scheduler/templates/ingressroute.yaml
charts/anaheim-job-scheduler/templates/license-validate-middleware.yaml
charts/anaheim-job-scheduler/templates/middleware.yaml
charts/anaheim-job-scheduler/templates/service.yaml
charts/anaheim-job-scheduler/values.yaml

add domainPath and necessary templates

feat: add domainPath and necessary templates

---

charts/anaheim-job-scheduler/Chart.yaml
charts/anaheim-job-scheduler/templates/NOTES.txt
charts/anaheim-job-scheduler/templates/hpa.yaml
charts/anaheim-job-scheduler/values.yaml

fix: service type error

---

charts/anaheim-job-scheduler/Chart.yaml
charts/anaheim-job-scheduler/values.yaml

add: status-middleware

---

charts/anaheim-job-scheduler/Chart.yaml
charts/anaheim-job-scheduler/templates/deployment.yaml
charts/anaheim-job-scheduler/values.yaml

add: graph env variables

---

charts/anaheim-job-scheduler/Chart.yaml
charts/anaheim-job-scheduler/templates/deployment.yaml

fix:  identation 2
